### ISSUE TITLE
Wrong download url for cbam_resnet50

### ISSUE THREAD

**Issue by chn-lee-yumi** [osmr/pytorchcv#1]
```
RuntimeError: Failed downloading url https://github.com/osmr/imgclsmob/releases/download/v0.0.537/cbam_resnet50-505-d8cf8488.pth.zip
```

When I change `505` to `0505` in https://github.com/osmr/pytorchcv/blob/607b96baa18646910981bc138a99f8a162b1b199/pytorchcv/models/common/model_metainfos.csv#L149 , it works.

Same problem with `efficientnet_b2b`.

**Comment by osmr** [comment]
Thanks. Fixed in v0.0.71.
